[project]
name = "my_project"
version = "0.1.0"
description = "A Python project template"
authors = [
    { name = "Your Name" }   # email optional
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "jupyter",
]
requires-python = ">=3.10"

[tool.uv]
# Always create a .venv folder in the project root
venv = ".venv"
