[project]
name = "UAV_SIM"
version = "0.1.0"
description = "An agent-based UAV simulator"
authors = [
    { name = "Michael SCHEEN" }   
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "jupyter",
    "mesa>=3.0.3",
    "seaborn>=0.13.2",
    "pytest>=8.4.1",
    "solara>=1.51.1",
    "networkx>=3.4.2",
    "altair>=5.5.0",
]
requires-python = ">=3.10"
